# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types:
      - created

# workflow tasks

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build-Macos
          run: GOOS=darwin GOARCH=amd64 go build -o ./dist/gofound_macos_amd64
      - name: Build-Macos-Arm64
          run: GOOS=darwin GOARCH=arm64 go build -o ./dist/gofound_macos_apple_silicon

      - name: Build-Windows-x64
          run: GOOS=windows GOARCH=amd64 go build -o ./dist/gofound_windows_amd64.exe

      - name: Build-Windows-AMR64
          run: GOOS=windows GOARCH=arm64 go build -o ./dist/gofound_windows_arm64.exe

      - name: Build-Linux-x64
          run: GOOS=linux GOARCH=amd64 go build -o ./dist/gofound_linux_amd64

      - name: Build-Linux-AMR64
          run: GOOS=linux GOARCH=arm64 go build -o ./dist/gofound_linux_arm64



      # step 2: generate build files
#      - name: Generate build files
#        uses: thatisuday/go-cross-build@v1
#        with:
#          platforms: "linux/amd64, darwin/amd64, windows/amd64"
#          name: "go-workflow"
#          compress: "true"
#          dest: "dist"

      # step 3: upload build-artifacts
      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"